name: Distcheck

on:
  push:
  pull_request:
  schedule:
  - cron: "0 20 * * 0-6"

jobs:
  skip_duplicates:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        # pin to unreleased SHA so we can use 'same_content_newer'
        # see https://github.com/fkirc/skip-duplicate-actions/pull/112
        uses: fkirc/skip-duplicate-actions@98d1dc89f43a47f8e4fba8e1c1fb8d6c5fc515ee
        with:
          concurrent_skipping: 'same_content_newer'
          skip_after_successful_duplicate: 'true'
          paths_ignore: '[]' # changes in any file can affect distcheck
          do_not_skip: '["workflow_dispatch", "schedule"]'

  Distcheck:
    needs: skip_duplicates
    if: ${{ needs.skip_duplicates.outputs.should_skip != 'true' }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]

    env:
      CC: ${{matrix.compiler}}
      VERBOSE: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install packages
      run: |
        needed=libperl-critic-perl
        if [ "$CC" = clang ]; then
          needed="clang $needed"
        fi
        sudo apt-get install $needed
    - name: Versions of build tools
      run: ./build-aux/ci-log-dependency-versions
    - name: Bootstrap
      run: ./autogen.sh
    - name: Configure
      run: ./configure --enable-obsolete-api --enable-hashes=all
    - name: Test
      run: make distcheck || (find . -name test-suite\*.log -print -a -exec cat '{}' ';'; exit 1)
